apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: uiptel
  labels:
    app: admin
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: ${DIGEST_IMAGE}
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            value: production
          - name: API_URL
            value: https://uiptel.com/api
          - name: DIGEST_IMAGE
            value: ${DIGEST_IMAGE}
        ports:
          - containerPort: 80
