apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: admin
  namespace: uiptel
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
      - uiptel.com
    secretName: uiptel-tls-cert
  rules:
  - host: uiptel.com
    http:
      paths:
      - path: /admin(/|$)(.*)
        backend:
          serviceName: admin
          servicePort: 80
