version:  '3.7'

services:
  admin:
    container_name: '${APP_NAME}_${APP_ENV}'
    image: '${APP_NAME}_${APP_ENV}:${APP_VERSION:-local}'
    hostname: '${APP_NAME}'
    working_dir: ${APP_PATH}
    command: ["sleep.js"]
    environment:
      EXTEND_ESLINT: 'true'
      NODE_ENV: development
    build:
      context: .docker/${APP_ENV}
      args:
        USER_NAME: ${USER_NAME}
        USER_ID: ${USER_UID}
    volumes:
      - /home/${USER_NAME}:/home/${USER_NAME}
      - ./:${APP_PATH}
    ports:
      - "3010:3000"
      - "5000:5000"

networks:
  default:
    driver: bridge
    name: ${BRIDGE}
