version:  '3.7'

services:
  nginx:
    image: nginx:stable-alpine
    command:  ["nginx", "-g", "daemon off;"]
    working_dir: /usr/share/nginx/html
    environment:
      NODE_ENV: development
    depends_on:
      - admin
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./.docker/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80

  admin:
    container_name: ${CONTAINER_NAME}
    image: ${DEV_IMAGE}
    hostname: ${APP_NAME}
    working_dir: ${APP_PATH}
    entrypoint: entrypoint.sh
    command: ["sleep.js"]
    environment:
      EXTEND_ESLINT: 'true'
      NODE_ENV: development
      BUILD_DATE: ${BUILD_DATE}
      VCS_REF: ${VCS_REF}
      VERSION: ${APP_VERSION}
      API_URL: https://uiptel.com/api
      APP_VARS: "BUILD_DATE VCS_REF VERSION API_URL NODE_ENV"

    volumes:
      - /home/${USER_NAME}:/home/${USER_NAME}
      - ./:${APP_PATH}
      - ./.docker/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    ports:
      - "3010:3000"

networks:
  default:
    driver: bridge
    name: ${NAMESPACE}
