version:  '3.7'

services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - admin
    volumes:
      - ./.docker/dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./build:/usr/share/nginx/html:ro
    ports:
      - 80:80

  admin:
    container_name: '${APP_NAME}_${APP_ENV}'
    image: '${APP_NAME}_${APP_ENV}:${APP_VERSION:-local}'
    hostname: '${APP_NAME}'
    working_dir: ${APP_PATH}
    command: ["sleep.js"]
    environment:
      EXTEND_ESLINT: 'true'
      NODE_ENV: development
    build:
      context: .docker/${APP_ENV}
      args:
        USER_NAME: ${USER_NAME}
        USER_ID: ${USER_UID}
    volumes:
      - /home/${USER_NAME}:/home/${USER_NAME}
      - ./:${APP_PATH}
    ports:
      - "3010:3000"

networks:
  default:
    driver: bridge
    name: ${NAMESPACE}
