version:  '3.7'

services:
  admin:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE}
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        NODE_ENV: production
        BUILD_DATE: ${BUILD_DATE}
        VCS_REF: ${VCS_REF}
        VERSION: ${APP_VERSION}
        API_URL: https://uiptel.com/api
        WORKDIR: /usr/share/nginx/html
    ports:
      - 80:80

networks:
  default:
    driver: bridge
    name: ${NAMESPACE}
