version:  '3.7'

services:
  nginx:
    image: nginx:stable-alpine
    working_dir: /usr/share/nginx/html
    depends_on:
      - admin
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 81:80

  admin:
    container_name: ${CONTAINER_NAME}
    image: ${DEV_IMAGE}
    hostname: ${APP_NAME}
    working_dir: ${APP_PATH}
    entrypoint: entrypoint.sh
    command: ["sleep.js"]
    environment:
      EXTEND_ESLINT: 'true'
      NODE_ENV: development
      BUILD_DATE: ${BUILD_DATE}
      VCS_REF: ${VCS_REF}
      VERSION: ${APP_VERSION}
      API_URL: http://localhost:3000
      APP_VARS: "BUILD_DATE VCS_REF VERSION API_URL NODE_ENV"

    volumes:
      - /home/${USER_NAME}:/home/${USER_NAME}
      - ./:${APP_PATH}
      - ./.docker/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - ./.docker/encode_vars.sh:/usr/local/bin/encode_vars.sh:ro
    ports:
      - "3010:3000"

networks:
  default:
    driver: bridge
    name: ${NAMESPACE}
